Repository caffe2/caffe2, pull requests merged in 2018-02, with the labels that each got.

#1930 Explicitly pass data on run call for caffe2.ai.
  _docs/tutorial-loading-pre-trained-models.md
  _docs/zoo.md
Labels: CLA Signed

#1931 Minor doc updates
  _docs/getting-started/mac.md
  _docs/getting-started/ubuntu.md
  _docs/tutorials.md
Labels: CLA Signed

#1934 Adding 'full' version of conda build
  conda/cuda_full/build.sh
  conda/cuda_full/conda_build_config.yaml
  conda/cuda_full/meta.yaml
  docker/jenkins/common/install_nccl.sh
  docker/jenkins/ubuntu-cuda/Dockerfile
  scripts/build_anaconda.sh
Labels: CLA Signed

#1989 Avoid having two protobuf on ubuntu14.04
  docker/jenkins/common/install_base.sh
Labels: CLA Signed

#1921 Move onnx-caffe2 inside caffe2
  caffe2/python/onnx/__init__.py
  caffe2/python/onnx/backend.py
  caffe2/python/onnx/backend_rep.py
  caffe2/python/onnx/bin/conversion.py
  caffe2/python/onnx/error.py
  caffe2/python/onnx/frontend.py
  caffe2/python/onnx/helper.py
  caffe2/python/onnx/tests/caffe2_ref_test.py
  caffe2/python/onnx/tests/conversion_test.py
  caffe2/python/onnx/tests/helper_test.py
  caffe2/python/onnx/tests/onnx_backend_test.py
  caffe2/python/onnx/tests/optimize_onnx_test.py
  caffe2/python/onnx/tests/ssa_test.py
  caffe2/python/onnx/tests/test_utils.py
  caffe2/python/onnx/workspace.py
  docker/jenkins/common/install_python.sh
Labels: CLA Signed

#1979 Allow more backends in caffe2_benchmark
  caffe2/share/contrib/binaries/caffe2_benchmark/CMakeLists.txt
  caffe2/share/contrib/binaries/caffe2_benchmark/caffe2_benchmark.cc
Labels: CLA Signed

#1976 Remove gf library in MKL
  cmake/Modules/FindMKL.cmake
Labels: CLA Signed

#1961 [wip] Fix public protobuf interface - wip
  .jenkins/build.sh
  CMakeLists.txt
  caffe/proto/CMakeLists.txt
  caffe2/proto/CMakeLists.txt
  cmake/Caffe2Config.cmake.in
  cmake/Dependencies.cmake
  cmake/ProtoBuf.cmake
  cmake/Summary.cmake
  cmake/public/gflags.cmake
  cmake/public/glog.cmake
  cmake/public/protobuf.cmake
Labels: CLA Signed

#1991 Update onnx version to include the model files suffix change
  docker/jenkins/common/install_python.sh
Labels: CLA Signed

#1981 Add an option in cmake for specifying caffe2 python lib relative installation path
  caffe2/CMakeLists.txt
Labels: CLA Signed

#1997 Adding guards around adding protobuf targets
  cmake/public/protobuf.cmake
Labels: CLA Signed

#2000 Support convolution without bias in NNPACK bindings
  caffe2/share/contrib/nnpack/conv_op.cc
Labels: CLA Signed

#1993 wip: cuda targets
  CMakeLists.txt
  caffe2/CMakeLists.txt
  cmake/Caffe2Config.cmake.in
  cmake/Dependencies.cmake
  cmake/Modules/FindCuDNN.cmake
  cmake/public/cuda.cmake
Labels: CLA Signed

#2010 Changing Anaconda-builds to the default recommended installation
  _docs/getting-started/centos.md
  _docs/getting-started/mac.md
  _docs/getting-started/ubuntu.md
  _docs/getting-started/windows.md
  _includes/doc-getting-started.html
Labels: CLA Signed

#2008 added debug info to OperatorDef
  caffe2/proto/caffe2.proto
  caffe2/python/core.py
Labels: CLA Signed

#2012 Focusing on binaries by default
  _includes/doc-getting-started.html
Labels: CLA Signed

#2011 add third output in onnx -> caffe2 lstm conversion
  caffe2/python/onnx/backend.py
Labels: CLA Signed

#2013 Fix all the broken tests from adding debug info
  caffe2/python/core_gradients_test.py
  caffe2/python/core_test.py
Labels: CLA Signed

#2016 Rename caffe2_ref_test.py to c2_ref_test.py
  caffe2/python/onnx/tests/c2_ref_test.py
Labels: CLA Signed

#2002 Install onnx by using the onnx inside caffe2
  .jenkins/build.sh
  docker/jenkins/common/install_python.sh
Labels: CLA Signed

#2004 Fixing an error building with CUDA on windows
  cmake/Utils.cmake
  cmake/public/cuda.cmake
Labels: CLA Signed

#2018 [DT] [4/n] Make epoch_group explicit for JobRunner
  caffe2/python/checkpoint.py
Labels: CLA Signed

#2030 Only focus on binaries for ubuntu, centos, and mac
  _docs/getting-started/android.md
  _docs/getting-started/centos.md
  _docs/getting-started/ios.md
  _docs/getting-started/raspbian.md
  _docs/getting-started/tegra.md
  _includes/doc-getting-started.html
Labels: CLA Signed

#2020 Remove build_host_protoc.bat
  scripts/build_host_protoc.bat
  scripts/build_windows.bat
Labels: CLA Signed

#2031 [WIP] splitting conda-builds into separate build and test phases for PRs
  .jenkins/build.sh
  .jenkins/test.sh
  scripts/build_anaconda.sh
  scripts/build_local.sh
Labels: CLA Signed

#2038 Add docker cmake3 install for ubuntu 14.04
  docker/jenkins/common/install_base.sh
Labels: CLA Signed

#2037 Add eigen version check
  caffe2/operators/conv_op_eigen.cc
Labels: CLA Signed

#2021 Update CMake min requirement to 3, and use interface library for cuda libs.
  .jenkins/build.sh
  CMakeLists.txt
  cmake/public/cuda.cmake
Labels: CLA Signed

#2005 Skip Cast ONNX backend test, which is not supported in Float16 case
  caffe2/python/onnx/tests/onnx_backend_test.py
Labels: CLA Signed

#2033 Pin libnccl2 to version 2.1.2
  docker/jenkins/common/install_nccl.sh
Labels: CLA Signed, build

#2045 Remove the use of EXTERNAL_DEPENDENCIES
  caffe2/CMakeLists.txt
  caffe2/contrib/aten/CMakeLists.txt
  cmake/Dependencies.cmake
  cmake/External/nccl.cmake
Labels: CLA Signed

#1817 no_bias in resnet32x32
  caffe2/python/models/resnet.py
Labels: CLA Signed

#2049 Move caffe_option to proper cmake_dependent_option
  cmake/Modules/FindMKL.cmake
  cmake/Utils.cmake
Labels: CLA Signed

#2034 [C2] Implement Layer-wise Adaptive Rate Scaling (LARS)
  caffe2/python/operator_test/lars_test.py
  caffe2/python/optimizer.py
  caffe2/python/optimizer_test.py
  caffe2/sgd/lars_op.cc
  caffe2/sgd/lars_op.h
Labels: CLA Signed

#2055 RNN ONNX export: concat hidden/cell states on the right axis
  caffe2/python/onnx/backend.py
Labels: CLA Signed

#2050 [cmake] try removing caffe2_include_directories hack
  cmake/Dependencies.cmake
  cmake/Utils.cmake
Labels: CLA Signed

#2063 Remove onnx-caffe2 reference
  caffe2/contrib/aten/docs/pytorch_to_caffe2.md
  caffe2/contrib/aten/docs/sample.py
Labels: CLA Signed

#2057 Transpose shape inference
  caffe2/python/onnx/backend.py
Labels: CLA Signed

#2059 OSS Playground modulelized model components
  caffe2/contrib/__init__.py
  caffe2/contrib/playground/AnyExp.py
  caffe2/contrib/playground/AnyExpOnTerm.py
  caffe2/contrib/playground/ModuleRegister.py
  caffe2/contrib/playground/README.md
  caffe2/contrib/playground/__init__.py
  caffe2/contrib/playground/checkpoint.py
  caffe2/contrib/playground/compute_loss.py
  caffe2/contrib/playground/compute_topk_accuracy.py
  caffe2/contrib/playground/meter.py
  caffe2/contrib/playground/module_map.py
  caffe2/contrib/playground/output_generator.py
  caffe2/contrib/playground/resnet50demo/IN1k_resnet50.py
  caffe2/contrib/playground/resnet50demo/__init__.py
  caffe2/contrib/playground/resnet50demo/caffe2_resnet50_default_forward.py
  caffe2/contrib/playground/resnet50demo/caffe2_resnet50_default_param_update.py
  caffe2/contrib/playground/resnet50demo/explicit_resnet_forward.py
  caffe2/contrib/playground/resnet50demo/explicit_resnet_param_update.py
  caffe2/contrib/playground/resnet50demo/gfs_IN1k.py
  caffe2/contrib/playground/resnet50demo/rendezvous_filestore.py
Labels: CLA Signed, model zoo

#2062 Fix caffe_add_whole_archive_flag in cmake
  cmake/Utils.cmake
Labels: CLA Signed

#2067 Cleanup CMake files and build scripts for Android
  CMakeLists.txt
  caffe2/CMakeLists.txt
  caffe2/mobile/contrib/arm-compute/README.md
  cmake/Dependencies.cmake
  scripts/build_android.sh
Labels: CLA Signed

#2070 Fix cuda full
  conda/cuda_full/build.sh
  conda/cuda_full/meta.yaml
  docker/jenkins/common/install_anaconda.sh
  scripts/build_anaconda.sh
Labels: CLA Signed

#2066 [wip] Cmake modernization
  CMakeLists.txt
  caffe2/CMakeLists.txt
  caffe2/share/contrib/binaries/caffe2_benchmark/CMakeLists.txt
  cmake/BuildVariables.cmake
  cmake/Caffe2Config.cmake.in
  cmake/Dependencies.cmake
  cmake/MiscCheck.cmake
  cmake/ProtoBuf.cmake
  cmake/Utils.cmake
  cmake/public/cuda.cmake
  cmake/public/utils.cmake
Labels: CLA Signed

#2078 Fix cmake dependency error in static library case. Peer coded with @bddppq
  caffe2/CMakeLists.txt
  cmake/Utils.cmake
  cmake/public/utils.cmake
Labels: CLA Signed

#2058 Fix Caffe2 ==> ONNX converter to handle three models
  caffe2/python/onnx/frontend.py
  caffe2/python/onnx/tests/__init__.py
  caffe2/python/onnx/tests/c2_ref_test.py
Labels: CLA Signed

#2081 Removing leveldb for ubuntu
  conda/cuda_full/build.sh
  conda/cuda_full/meta.yaml
Labels: CLA Signed

#2069 ONNX RNN export: add some padding to mimic pytorch
  caffe2/operators/variable_length_sequence_padding.cc
  caffe2/operators/variable_length_sequence_padding.h
  caffe2/python/onnx/backend.py
Labels: CLA Signed
